### ISSUE TITLE
I cant view my projects on my dashboard unlike the landing page

### ISSUE THREAD

**Issue by unicodeveloper** [andela/pibbble#138]
On the landing page, people can view more details about a project by just clicking on the title.

I should be able to do the same on my dashboard.

<img width="1053" alt="screen shot 2015-11-22 at 1 40 09 pm" src="https://cloud.githubusercontent.com/assets/2946769/11323242/ac436078-911e-11e5-8cfa-6dcc8cf6a8cc.png">

**Comment by sirolad** [comment]
This issue has been resolved.

Best Regards,

_Surajudeen Akande_
Software Developer, _Andela_
+2348037690966 | Skype: sirolad https://webapp.wisestamp.com/#
http://facebook.com/runthinz  http://twitter.com/babatoclean1
http://github.com/andela-sakande

**Comment by unicodeveloper** [comment]
The feature still doesnt work..I just tried it. What's happening?

**Comment by unicodeveloper** [comment]
It works now but why is it like this? 

Why is the project and sidebar occupying the whole screen? 

<img width="1117" alt="screen shot 2015-11-23 at 3 36 49 pm" src="https://cloud.githubusercontent.com/assets/2946769/11336661/36bef09e-91f8-11e5-9544-bb6760d7d4dd.png">

**Comment by sirolad** [comment]
This issue has been resolved.
